name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'
      message:
        description: 'Custom message'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Greet
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          if [ -n "${{ github.event.inputs.message }}" ]; then
            echo "Custom message: ${{ github.event.inputs.message }}"
          fi

      - name: Print job info
        run: |
          echo "This job was triggered manually."
          echo "Runner: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
