name: Release Github action for CLI

on:
  release:
    types:
      - prereleased

jobs:
  release-action-yml:
    name: Release github action for cli and update version in action.yml
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Get version without v character
        id: version
        run: |
          VERSION=${{github.event.release.tag_name}}
          VERSION_WITHOUT_V=${VERSION:1}
          echo "value=${VERSION_WITHOUT_V}" >> $GITHUB_OUTPUT
      - name: Release to Docker
        run: |
          echo ${{env.DOCKER_PASSWORD}} | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin
          npm run action:docker:build
          docker tag asyncapi/github-action-for-cli:latest asyncapi/github-action-for-cli:${{ steps.version.outputs.value }}
          docker push asyncapi/github-action-for-cli:${{ steps.version.outputs.value }}
          docker push asyncapi/github-action-for-cli:latest

      - name: Update action.yml with version
        run: |
          VERSION=${{ steps.version.outputs.value }}
          sed "s/\\\${ version }/${VERSION}/g" action-template.yml > action.yml

      - name: Create branch
        run: |
          git checkout -b update-action-docker-version-${{ github.sha }}

      - name: Commit and push
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
          git add action.yml
          git commit -m "chore(action): update docker version in action.yml"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/cli

      - name: Create PR
        run: |
          gh pr create --title "chore(action): update docker version in action.yml" --body "Updated docker version of github action in action.yml" --head "update-action-docker-version-${{ github.sha }}"
