name: Update Github Action YML

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update in action.yml'
        required: true

jobs:
  update-action-yml:
    name: Update docker version of github action in action.yml
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update action.yml with version
        run: |
          VERSION=${{ github.event.inputs.version }}
          sed "s/\${{ version }}/${VERSION}/g" action-template.yml > action.yml

      - name: Create branch
        run: |
          git checkout -b update-action-docker-version-${{ github.sha }}

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add action.yml
          git commit -m "chore(action): update docker version in action.yml"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/cli

      - name: Create PR
        run: |
          gh pr create --title "chore(action): update docker version in action.yml" --body "Updated docker version of github action in action.yml" --head "update-action-docker-version-${{ github.sha }}"
